Infinispan cache configuration
This cheat sheet shows Infinispan cache configuration options and capabilities that help you to achieve the best performance for your Infinispan deployment.

.Clustered cache modes
Distributed:: Distributed caches offer linear scalability and efficient memory usage by creating fewer copies of each entry across the cluster.
+
Number of owners: Distributed caches store a number of copies for each cache entry that is equal to the Number of owners that you configure.
Replicated:: Replicated caches offer data guarantees and fault tolerance by creating a copy of all entries on each node in the cluster.

.Cluster replication
Synchronous replication:: Helps to keep your data consistent but adds latency to cluster traffic that reduces throughput for cache writes.
Asynchronous replication:: Reduces latency and increases the speed of write operations but leads to data inconsistency and provides a lower guarantee against data loss.

== Cache configuration options

Encoding:: A format, identified by a media type, that Infinispan uses to store keys and values.
+
TIP: Infinispan recommends the application/x-protostream media type. Protobuf gives you excellent performance as well as interoperability between client applications in different programming languages for both Hot Rod and REST endpoints.

Media types for cache encoding:

Protobuf = 'application/x-protostream',
Java = 'application/x-java-object',
JavaSerialized = 'application/x-java-serialized',
XML = 'application/xml; charset=UTF-8',
JSON = 'application/json',
Text = 'text/plain',
JBoss = 'application/x-jboss-marshalling',
Octet = 'application/octet-stream',
Empty = 'Empty'


Expiration::
Expiration removes entries based on a lifespan or maximum idle time and takes effect across clusters.
Lifespan: The maximum amount of time, in milliseconds, that cache entries can exist. If you set the value to -1, entries never expire.
Max-idle: The maximum amount of time, in milliseconds, that cache entries can remain idle. If no operations are performed on entries within the maximum idle time, the entries expire across the cluster. If you set the value to -1, entries never expire.

Statistics: Enable collecting statistics for your cache. Keep disabled for optimal performance. 

Infinispan capabilities

Bounded 
Indexed
Authorization
Backups
Transactional
Persistent

== Bounded caches 
Control the size of the cache by configuring Infinispan to evict entries.

.Eviction strategies
Eviction always takes place when you define either the max-size or the max-count (but not both) for the data container. 
Max size:: Defines the size of the data container in bytes. Eviction occurs when the approximate memory usage of the data container exceeds the maximum size.
Max count:: Defines the size of the data container by number of entries. Eviction occurs after the container size exceeds the maximum count.

If no strategy is defined, but max-count or max-size is configured, REMOVE is used.
Remove:: Automatically evict older entries to make space for new entries. By default REMOVE is always used when you define a size for the data container.
Exception:: Throw ContainerFullException and prevent new entries from being created. You can use this strategy only with transactional caches that use two phase commits.

== Indexing caches
Create indexes of values in your caches for faster queries and full-text search capabilities.

.Indexing options for cache
Index storage::

By default, Infinispan stores indexes in persistent storage. Persistent storage saves the index on the host file system so the index is available between restarts. Volatile storage saves the index in JVM heap memory, which means that the index does not survive restarts. You should configure volatile index storage only for small datasets.

Index startup mode::
Indexing operations that ensure the index is consistent with data in the cache.
Purge: Clears the index when the cache starts. 
Reindex: Rebuilds the index when the cache starts.
Auto: Automatically triggers an indexing operation when the cache starts. If data is volatile and the index is persistent then the cache is cleared when it starts. If data is persistent and the index is volatile then the cache is reindexed when it starts.
None: Cache startup does not trigger an indexing operation. This is the default value.

Indexed entity:: The fully qualified class names of the entities you want Infinispan to include when building the index.

== Index tuning
Control how Infinispan interacts with an index to optimize performance.

.Index reader: 
Refresh interval: Interval, in milliseconds, to reopen the index reader. By default Infinispan reads the index before each query if the index changed since the last refresh. Configuring with a value larger than zero will make some queries results stale, but query throughput will increase substantially, specially in write heavy scenarios.

	.Index writer configuration attributes
Commit interval: Amount of time, in milliseconds, that index changes that are buffered in memory are flushed to the index storage and a commit is performed. Because operation is costly, small values should be avoided. The default is 1000 ms (1 second).
Low level trace: Enables low-level trace information for indexing operations. Low-level tracing degrades performance and you should use it only as a last resource for troubleshooting.
Max buffered entries: Maximum number of entries that can be buffered in-memory before they are flushed to the index storage. Large values result in faster indexing but use more memory. When used in combination with the `ram-buffer-size` attribute, a flush occurs for whichever event happens first.
Queue count: Number of internal queues to use for each indexed type. Each queue holds a batch of modifications that is applied to the index and queues are processed in parallel. Increasing the number of queues leads to an increase of indexing throughput, but only if the bottleneck is CPU. For optimum results, do not set a value for `queue-count` that is larger than the value for `thread-pool-size`.
Queue size: Maximum number of elements each queue can hold. Increasing the `queue-size` value increases the amount of memory that is used during indexing operations. Setting a value that is too small can block indexing operations.
RAM buffered size: Maximum amount of memory that can be used for buffering added entries and deletions before they are flushed to the index storage. Large values result in faster indexing but use more memory. For faster indexing performance you should set this attribute instead of `max-buffered-entries`. When used in combination with the `max-buffered-entries` attribute, a flush occurs for whichever event happens first.
Thread pool size: Number of threads that execute write operations to the index.

	.Indexed merge configuration attributes:
Calibrate by deletes: Whether the number of deleted entries in an index should be taken into account when counting the entries in the segment. Setting `false` will lead to more frequent merges caused by `max-entries`, but will more aggressively merge segments with many deleted documents, improving search performance.
Factor: Number of segments that are merged at once. With smaller values, merging happens more often, which uses more resources, but the total number of segments will be lower on average, increasing search performance. Larger values (greater than 10) are best for heavy writing scenarios.
Max entries: Maximum number of entries that an index segment can have before merging. Segments with more than this number of entries are not merged. Smaller values perform better on frequently changing indexes, larger values provide better search performance if the index does not change often.
Min size: Minimum target size of segments, in MB, for background merges. Segments smaller than this size are merged more aggressively. Setting a value that is too large might result in expensive merge operations, even though they are less frequent.
Max size: Maximum size of segments, in MB, for background merges. Segments larger than this size are never merged in the background. Settings this to a lower value helps reduce memory requirements and avoids some merging operations at the cost of optimal search speed. This attribute is ignored when forcefully merging an index and `max-forced-size` applies instead.
Max forced size: maximum size of segments, in MB, for forced merges and overrides the `max-size` attribute. Set this to the same value as `max-size` or lower. However setting the value too low degrades search performance because documents are deleted.

== Authorization:
Authorization secures your deployment by restricting access to data based on user roles and permissions.
Default set of roles
Observer
Application
Admin
Monitor
Deployer



== Cache backups:
Defines backup locations for cache data and modifies state transfer properties.

Merge policy:: A policy on how Infinispan resolves conflicting entries between backup locations when using the ASYNC strategy. You can specify one of the default merge policies or the fully qualified name of a class that implements the XSiteEntryMergePolicy interface.

Maximum cleanup delay:: The maximum delay, in milliseconds, between which tombstone cleanup tasks run when using the ASYNC strategy.

Number of tombstone:: Specify the target number of tombstones, or key metadata, to store when using the ASYNC strategy. If the number of tombstones increases beyond this number then Infinispan runs the cleanup task more frequently. Likewise, if the number of tombstones is less than this number then Infinispan does not run the cleanup task as frequently.

Site configuration: 
Site name: Names the remote site to which the cache backs up data.
Backup strategies: Sets the strategy for backing up to a remote site.
ASYNC
SYNC
Failure policy: Controls how local writes to caches are handled if synchronous backup operations fail.
Ignore: Ignore failed backup operations and write to the local cache.
Warn: Log exceptions when backup operations fail and write to the local cache.
Fail: Throw exceptions when backup operations fail and attempt to stop writes to the local cache.
Custom: Use a custom failure policy. Requires the "failure-policy-class" attribute.
Timeout: Specify the timeout, in milliseconds, for synchronous and asynchronous backup operations.
Failure policy class: Specify the fully qualified name of a class that implements the CustomFailurePolicy interface if you select CUSTOM as the failure policy.
Take offline: Operations to replicate data across clusters are resource intensive. To excessive resource usage Infinispan can take backup locations offline automatically.
After failures: Set the number of consecutive failures that can occur for backup operations before sites go offline. Specify a negative or zero value to use minimum wait time only.
Minimum wait: Sets the minimum time to wait, in milliseconds, before sites go offline when backup operations fail. If subsequent operations are successful, the minimum wait time is reset. If you set "after-failures", sites go offline when the wait time is reached and the number of failures occurs.
State transfer: Modify state transfer operations that synchronize data between sites.
State transfer mode: Control whether state transfer happens manually on user action, which is the default, or automatically when backup locations come online. Infinispan can perform automatic state transfer with the ASYNC backup strategy only.
Manual: Users must bring backup locations online and initiate state transfer between remote sites.
Auto: Backup locations that use the asynchronous backup strategy can automatically come back online. State transfer operations begin when the remote site connections are stable.
Chunk size: Specify how many cache entries are batched in each transfer request.
Timeout: Specify the time to wait, in milliseconds, for the backup site to acknowledge the state chunk received and applied. The default value is 20 minutes.
Maximum retries: Set the maximum number of retry attempts for push state failures. Specify a value of 0 (zero) to disable retry attempts. The default value is 30.
Wait time: Set the amount of time, in milliseconds, to wait between retry attempts for push state failures. You must specify a value of 1 or more. The default value is 2000.

If the cache receives updates from a cache with a different name:
	Cache name: Specifies the name of the remote cache that uses the local cache as a backup.
	Remote site: Specifies the name of the remote site that backs up data to the local cache.

== Transactional: 

Transaction mode: Configure the mode that Infinispan uses when carrying out transactions to ensure the cache state is consistent.
NON_XA: Cache will enlist within transactions as a javax.transaction.Synchronization.
NON_DURABLE_XA: Cache will enlist within transactions as a javax.transaction.xa.XAResource, without recovery.
FULL_XA: Cache will enlist within transactions as a javax.transaction.xa.XAResource, with recovery.

Locking mode: Configure how Infinispan locks keys to perform write operations for transactions. Locking keys adds contention that increases latency for write operations. You can adjust the amount of contention by using optimistic or pessimistic locking.
Optimistic: Infinispan locks keys when it invokes the commit() method. Keys are locked for shorter periods of time which reduces overall latency but makes transaction recovery less efficient.
Pessimistic: Infinispan locks keys when it invokes the put() method. Keys are locked for longer periods of time which increases latency but makes transaction recovery more efficient.

Read isolation level: Read isolation levels guarantee whether or not data in the cache has changed during a transaction.
Repeatable read: Read operations return the same value that Infinispan initially retrieves for an entry during a transaction. This is the default read isolation level because it guarantees consistency.
Read committed: Read operations might return different values if another transaction modifies the entries.
Stop timeout: Sets the amount of time, in milliseconds, that Infinispan waits for ongoing transactions when the cache is stopped.

Complete timeout: Sets the maximum amount of time, in milliseconds, that transactions can run. Infinispan aborts transactions that do not completed before reaching the timeout.

Reaper interval: Sets the amount of time, in milliseconds, between which Infinispan checks if transactions are complete.

Transaction manager lookup: Specifies a lookup class that returns the TransactionManager to initialize.

Recovery cache: Specifies the cache that stores information to recover in-doubt transactions.

== Persistence: 
Configure non-volatile storage so entries remain available after cluster restarts.

Passivation: Infinispan writes entries to persistent storage when it evicts those entries from memory. Passivation ensures that only a single copy of an entry is maintained, either in-memory or in a cache store, and prevents unnecessary and expensive writes to persistent storage.

Connection attempts: The number of times Infinispan tries to connect to the cache store. The default value is 10.

Connection interval: An interval, in milliseconds, between connection attempts. The default value is 50.

Availability interval: An interval, in milliseconds, between which Infinispan polls the cache store to ensure it is available. The default value is 1000.

Persistent storage configuration: 
File store: File-based cache store on the local host filesystem. For clustered caches, file-based cache stores are unique to each Infinispan node.
Remote store: Remote cache stores use the Hot Rod protocol to store data on Infinispan clusters.
Table SQL store: Load entries from a single database table. Ensure that the appropriate JDBC driver is available to the Infinispan cluster.
Query SQL store: Use SQL queries to load entries from one or more database tables, including sub-columns. You can also perform insert, update, and delete operations. You must ensure that the appropriate JDBC driver is available to the Infinispan cluster.
JDBC string-based store: Use a relational database for persistent storage through a JDBC connection. Ensure that the appropriate JDBC driver is available to the Infinispan cluster.
RocksDB store: A RocksDB cache store uses two databases; one as a primary store and another to hold expired entries.
Custom store: Use a custom cache store that you implement with the Infinispan Persistence SPI.

Advanced/cache tuning 
Storage type: JVM heap is a managed memory space. Off-heap storage is native system memory outside JVM memory management. Off-heap storage uses less memory per entry compared with JVM heap storage and can improve performance by avoiding garbage collection (GC) runs.

Concurrency level: Configures the number of locks to create in the shared pool for lock striping.

Lock timeout: The amount of time, in milliseconds, to wait for a contented lock.

Lock striping: Uses a shared pool of locks for all entries in the cache. Striping lowers the memory footprint for locks but can reduce concurrency. If you disable striping, a lock is created for each entry in the cache.



