= Infinispan cache configuration cheat sheet
Use the following information and configuration examples as a quick reference for creating and configuring Infinispan caches.

== Clustered cache modes

Distributed:: Distributed caches offer linear scalability and efficient memory usage by creating fewer copies of each entry across the cluster.
Distributed caches store a number of copies for each cache entry that is equal to the *Number of owners* that you configure.
+
[source,xml]
----
<distributed-cache />
----

Replicated:: Replicated caches offer data guarantees and fault tolerance by creating a copy of all entries on each node in the cluster.
+
[source,xml]
----
<replicated-cache />
----

== Cluster replication

Synchronous replication:: Helps to keep your data consistent but adds latency to cluster traffic that reduces throughput for cache writes.
+
[source,xml]
----
<distributed-cache mode="SYNC" />
----
Asynchronous replication:: Reduces latency and increases the speed of write operations but leads to data inconsistency and provides a lower guarantee against data loss.
+
[source,xml]
----
<distributed-cache mode="ASYNC" />
----

== Cache configuration options

.Encoding
A format, identified by a media type, that Infinispan uses to store keys and values.

TIP: Infinispan recommends the `application/x-protostream` media type. Protobuf gives you excellent performance as well as interoperability between client applications in different programming languages for both Hot Rod and REST endpoints.

[source,xml]
----
<distributed-cache mode="SYNC">
  <encoding>
    <key media-type="application/x-protostream"/>
    <value media-type="application/x-protostream"/>
  </encoding>
</distributed-cache>
----

.Expiration
Expiration removes entries based on a lifespan or maximum idle time. Expiration takes effect across Infinispan clusters.

Lifespan:: The maximum amount of time, in milliseconds, that cache entries can exist. If you set the value to -1, entries never expire.

Max-idle:: The maximum amount of time, in milliseconds, that cache entries can remain idle. If no operations are performed on entries within the maximum idle time, the entries expire across the cluster. If you set the value to -1, entries never expire.

TIP: This would create a performance issue for get() update all instance, lifespan is better if very close.

[source,xml]
----
<distributed-cache>
  <expiration lifespan="5000"
              max-idle="1000" />
</distributed-cache>
----

.Statistics
Start collecting statistics for your cache. Keep disabled for optimal performance.

[source,xml]
----
<distributed-cache statistics="true" />
----

== Infinispan capabilities
* Bounded
* Indexed
* Authorization
* Backups
* Transactional
* Persistent

== Bounded caches
Control the size of the cache by configuring Infinispan to evict entries.

.Eviction
Eviction always takes place when you define either the max-size or the max-count (but not both) for the data container.

Max size:: Defines the size of the data container in bytes. Eviction occurs when the approximate memory usage of the data container exceeds the maximum size.
+
[source,xml]
----
<distributed-cache>
  <memory max-size="12MB" when-full="REMOVE"/>
</distributed-cache>
----

Max count:: Defines the size of the data container by number of entries. Eviction occurs after the container size exceeds the maximum count.
+
[source,xml]
----
<distributed-cache>
	<memory max-count="124" when-full="REMOVE"/>
</distributed-cache>
----

.Eviction strategies
* `REMOVE` Infinispan performs eviction. This is the default strategy when you define a size for the data container.

TIP: Would lead to cluster inconsistency if no persistence is configured.

* `EXCEPTION` Infinispan throws an exception instead of evicting entries.

If no strategy is defined, but max-count or max-size is configured, `REMOVE` is used.

== Indexed caches
Create indexes of values in your caches for faster queries and full-text search capabilities.

.Index storage
Persistent:: On the host file system, which is the default and persists indexes between restarts.
+
[source,xml]
----
<distributed-cache>
  <indexing storage="filesystem">
    <!-- Indexing configuration goes here. -->
  </indexing>
</distributed-cache>
----

Volatile:: In JVM heap memory, which means that indexes do not survive restarts. You should store indexes in JVM heap memory only for small datasets.
+
[source,xml]
----
<distributed-cache>
  <indexing storage="local-heap">
    <!-- Indexing configuration goes here. -->
  </indexing>
</distributed-cache>
----

Index reader:: The index reader provides access to the indexes to perform queries. As the index content changes, Infinispan needs to refresh the reader so that search results are up to date.
+
[source,xml]
----
<distributed-cache>
  <indexing storage="filesystem" path="${java.io.tmpdir}/baseDir">
    <!-- Sets an interval of one second for the index reader. -->
    <index-reader refresh-interval="1000"/>
    <!-- Additional indexing configuration goes here. -->
  </indexing>
</distributed-cache>
----

Index writer:: The index writer constructs an index composed of one or more segments (sub-indexes) that can be merged over time to improve performance.
+
[source,xml]
----
<distributed-cache>
  <indexing storage="filesystem" path="${java.io.tmpdir}/baseDir">
    <index-writer commit-interval="2000"
                  low-level-trace="false"
                  max-buffered-entries="32"
                  queue-count="1"
                  queue-size="10000"
                  ram-buffer-size="400"
                  thread-pool-size="2">
      <index-merge calibrate-by-deletes="true"
                   factor="3"
                   max-entries="2000"
                   min-size="10"
                   max-size="20"/>
    </index-writer>
    <!-- Additional indexing configuration goes here. -->
  </indexing>
</distributed-cache>
----

== Authorization
Secure your deployment by restricting user access to data.

.Default set of roles
* Observer
* Application
* Admin
* Monitor
* Deployer
+
[source,xml]
----
<distributed-cache>
	<security>
        <!-- Multiple roles can be used -->
		<authorization enabled="true"
                  roles="observer application admin monitor"/>
	</security>
</distributed-cache>
----

== Backups
Define backup locations for cache data and modify state transfer properties.

Backup strategy:: To back up data to a different cluster, Infinispan can use either a synchronous or asynchronous strategy.
Infinispan performs conflict resolution with the asynchronous backup strategy.

Remote site:: Specifies the name of the remote site that backs up data to the local cache.
Remote cache:: Specifies the name of the remote cache that uses the local cache as a backup.
Timeout:: Specifies timeout, in milliseconds, for synchronous and asynchronous backup operations.

[cols="a,a", options="header"]
|===
| Cluster LON
| Cluster NYC

|
[source,xml]
----
<distributed-cache>
  <backups>
    <backup site="NYC"
            strategy="ASYNC"
            timeout="10000" />
  </backups>
</distributed-cache>
----

|
[source,xml]
----
<distributed-cache name="eu-customers">
  <backups>
    <backup site="LON"
            strategy="ASYNC" />
  </backups>
    <!-- Defines the local cache as a backup for a remote cache with a different name. -->
  <backup-for remote-cache="customers"
              remote-site="LON" />
</distributed-cache>
----

|===

== Transactional

.Transaction mode
Configure the mode that Infinispan uses when carrying out transactions to ensure the cache state is consistent.

NON_XA:: Cache will enlist within transactions as a `javax.transaction.Synchronization`.
NON_DURABLE_XA:: Cache will enlist within transactions as a `javax.transaction.xa.XAResource`, without recovery.
FULL_XA:: Cache will enlist within transactions as a `javax.transaction.xa.XAResource`, with recovery.

.Locking mode
Configure how Infinispan locks keys to perform write operations for transactions. Locking keys adds contention that increases latency for write operations. You can adjust the amount of contention by using optimistic or pessimistic locking.

Optimistic:: Infinispan locks keys when it invokes the `commit()` method. Keys are locked for shorter periods of time which reduces overall latency but makes transaction recovery less efficient.
Pessimistic:: Infinispan locks keys when it invokes the `put()` method. Keys are locked for longer periods of time which increases latency but makes transaction recovery more efficient.
+
[source,xml]
----
<distributed-cache name="deee" mode="SYNC">
	<transaction
          <!-- Transaction mode -->
                mode="NON_XA"
          <!-- Locking mode -->
                locking="OPTIMISTIC"/>
</distributed-cache>
----

== Persistence
Configure non-volatile storage so entries remain available after cluster restarts.

.Passivation
Infinispan writes entries to persistent storage when it evicts those entries from memory. Passivation ensures that only a single copy of an entry is maintained, either in-memory or in a cache store, and prevents unnecessary and expensive writes to persistent storage.
[source,xml]
----
<distributed-cache>
  <persistence passivation="true">
    <!-- Persistence configuration goes here. -->
  </persistence>
</distributed-cache>
----

.Persistent storage configuration
File store:: File-based cache store on the local host filesystem. For clustered caches, file-based cache stores are unique to each Infinispan node.
+
[source,xml]
----
<distributed-cache>
	<persistence passivation="false">
		<file-store>
			<data path="path/to/data"/>
			<index path="path/to/index"/>
		</file-store>
	</persistence>
</distributed-cache>
----

Remote store:: Remote cache stores use the Hot Rod protocol to store data on Infinispan clusters.
Table SQL store:: Load entries from a single database table. Ensure that the appropriate JDBC driver is available to the Infinispan cluster.
Query SQL store:: Use SQL queries to load entries from one or more database tables, including sub-columns. You can also perform insert, update, and delete operations. You must ensure that the appropriate JDBC driver is available to the Infinispan cluster.
JDBC string-based store:: Use a relational database for persistent storage through a JDBC connection. Ensure that the appropriate JDBC driver is available to the Infinispan cluster.
RocksDB store:: A RocksDB cache store uses two databases; one as a primary store and another to hold expired entries.
Custom store:: Use a custom cache store that you implement with the Infinispan Persistence SPI.

== Configuration formats
Infinispan supports multiple configuration formats. You can use XML, JSON, or YAML to configure your deployment.

.XML
[source,xml]
----
<distributed-cache owners="2"
                   mode="SYNC"
                   statistics="true">
  <encoding media-type="application/x-protostream"/>
  <locking isolation="REPEATABLE_READ"/>
  <transaction mode="FULL_XA"
               locking="OPTIMISTIC"/>
  <expiration lifespan="5000"
              max-idle="1000" />
  <memory max-count="1000000"
          when-full="REMOVE"/>
  <indexing enabled="true"
            storage="local-heap">
    <index-reader refresh-interval="1000"/>
    <indexed-entities>
			<indexed-entity>org.infinispan.Person</indexed-entity>
		</indexed-entities>
  </indexing>
  <persistence passivation="false">
    <!-- Persistent storage configuration. -->
  </persistence>
</distributed-cache>

----

.JSON
[source,json]
----
{
  "distributed-cache": {
    "owners": 2,
    "mode": "SYNC",
    "statistics": true,
    "encoding": {
      "media-type": "application/x-protostream"
    },
    "locking": {
      "isolation": "REPEATABLE_READ"
    },
    "transaction": {
      "mode": "FULL_XA",
      "locking": "OPTIMISTIC"
    },
    "expiration": {
      "lifespan": 5000,
      "max-idle": 1000
    },
    "memory": {
      "max-count": 1000000,
      "when-full": "REMOVE"
    },
    "indexing": {
      "enabled": true,
      "storage": "local-heap",
      "indexed-entities": [
        "org.infinispan.Person"
      ],
      "index-reader": {
        "refresh-interval": 1000
      }
    },
    "persistence": {
      "passivation": false
    }
  }
}
----

.YAML
[source,yaml]
----
distributed-cache:
  owners: 2
  mode: SYNC
  statistics: true
  encoding:
    media-type: application/x-protostream
  locking:
    isolation: REPEATABLE_READ
  transaction:
    mode: FULL_XA
    locking: OPTIMISTIC
  expiration:
    lifespan: 5000
    max-idle: 1000
  memory:
    max-count: 1000000
    when-full: REMOVE
  indexing:
    enabled: true
    storage: local-heap
    index-reader:
      refresh-interval: 1000
    indexedEntities: 
      - "org.infinispan.Person"
  persistence:
    passivation: false
----
